### ISSUE TITLE
"npm start" server doesn't serve data.

### ISSUE THREAD

**Issue by mrbinky3000** [Snapkite/snapkite-engine#12]
When I run "npm start" I see the following in the CLI.

```shell
> snapkite-engine@0.1.2 start /Users/matt/Sites/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 3000
```

However, when I enter the address "http://localhost:3000" into Chrome.  The page times out after 2 minutes with an error stating that "no data was sent"

![Screenshot of Chrome](http://matthewtoledo.com/share/image/snapkite-no-data-sent.png)

I also tried http://127.0.0.1:3000 with the same results.

To be absolutely sure, I updated the application.socket.port value in the config.json file to 8080 and tried localhost:8080 and 127.0.01:8080 with the same results.

I tried setting a new password on twitter and resetting the Consumer Key and Consumer Secret Key.  Regenerating the Access Tokens doesn't change the values for Access Token Ke or Access Token Secret but I did it anyway.

I tried completely deleting the app on Twitter and making a new one, with new keys and new, different access tokens.  Still no change.

Xtools is installed.  I have gcc and make required by node-gyp.  Node-gyp compiled without errors.

Mac OSX El Capitan 10.11.13
node v5.0.0
npm v 3.5.3

I do not think it's a firewall issue as I am able to server other projects to port 3000 using things like node http-server, or php -S

**Comment by richpixel** [comment]
+1

Although not as thorough in my investigation, I'm having the same issue.

**Comment by aikinode** [comment]
If I am not mistaken it looks like both of you are following the learning sample of React.js Essentials book. I had some problems to get this working but finally, after fixing some typos , it worked as expected. 
If snapkite prints in the console the following message then you should be ok. 

[Snapkite][Socket] Listening on port 3000 

Additionally if your app is connecting properly to snapkite you should get the following message.

[Snapkite][Socket] Client connected

Also, if you want to see if snapkite is working you can add console.log(tweet) in your app.js located inside snapkite-engine directory just above the line that says  

global.io.emit('tweet', tweet);

After adding that, if you do npm start it will start showing different tweets in the console.

**Comment by richpixel** [comment]
Hi - yes, I'm following the React.js Essentials book. The strange thing is, everything appears fine, I see

[Snapkite][Socket] Listening on port 3000
[Snapkite][Socket] Client connected

And in my browser console for the snapterest app I have:

[Snapkite Stream Client] Socket connected

but no tweets are served, ever

I added the line to console.log a tweet, but nothing appears. I wonder if there's a verbose mode on the snapkite engine, something to log errors.

**Comment by richpixel** [comment]
fyi I reinstalled snapkite-engine and it works now. I think I may have failed to setup the filters properly.

**Comment by aikinode** [comment]
Great ! Now that you have snapkite-engine working you might try the console.log I recommended so that you see the output of the tweets that it receives.

**Comment by lifeeric** [comment]
But I have a different issue, can you please help me out these bugs

```
> snapkite-engine@0.1.2 start /home/me/codedir/react/react16/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 3000
/home/me/codedir/react/react16/snapkite-engine/node_modules/node-tweet-stream/lib/twitter.js:9
      throw new Error('Exceeded twitter rate limit')
      ^

Error: Exceeded twitter rate limit
    at Twitter.httpBackoff (/home/me/codedir/react/react16/snapkite-engine/node_modules/node-tweet-stream/lib/twitter.js:9:13)
    at Twitter.<anonymous> (/home/me/codedir/react/react16/snapkite-engine/node_modules/node-tweet-stream/lib/twitter.js:238:15)
    at Request.emit (events.js:189:13)
    at Request.onRequestResponse (/home/me/codedir/react/react16/snapkite-engine/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
```

**Comment by lifeeric** [comment]
now another error I'm getting!

```
> snapkite-engine@0.1.2 start /home/me/codedir/react/react16/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 8080
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/me/codedir/react/react16/snapkite-engine/filters/snapkite-filter-is-possibly-sensitive/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
```
